name: notes_login
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  google_fonts: ^4.0.3
  flutter_statusbarcolor_ns: ^0.5.0
  uuid: ^3.0.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
